[build-system]
requires = ["setuptools>=65", "wheel", "torch", "packaging"]
build-backend = "setuptools.build_meta"

[project]
name = "tilescale_ext"
version = "0.1.0"
requires-python = ">=3.8"
description = "TileScale unified CUDA/IPCs extension."
